### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by nution101** [tnqiang/Unity_ListView#1]
In TestListItem.cs if you put a larger number, say 100 instead of 10 on the for loop, the items in the list start to get kind of funky as you scroll to the right. Eventually clipping them off only showing one item by the end of the list. Noticed it happens when you start to push 24 off to the left of the screen. At least using the size / shape of the squares in your demo.

**Comment by tnqiang** [comment]
Thanks, fixed.
It is a bug when calculate the start index of the item to be shown.
