### ISSUE TITLE
Argument is out of range. - Test Scene

### ISSUE THREAD

**Issue by kevinan9** [tnqiang/Unity_ListView#2]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.GameObject].get_Item (Int32 index) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
NSUListView.USimpleListView.HideNonuseableItems () (at Assets/Standard Assets/UListView/USimpleListView.cs:153)
NSUListView.IUListView.RefreshListView () (at Assets/Standard Assets/UListView/IUListView.cs:120)
NSUListView.IUListView.OnValueChanged (Vector2 pos) (at Assets/Standard Assets/UListView/IUListView.cs:91)
UnityEngine.Events.InvokableCall`1[UnityEngine.Vector2].Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:168)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:602)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:744)
UnityEngine.Events.UnityEvent`1[UnityEngine.Vector2].Invoke (Vector2 arg0) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_1.cs:53)
UnityEngine.UI.ScrollRect.LateUpdate () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/ScrollRect.cs:344)

**Comment by tnqiang** [comment]
Thanks, this is a bug when calculate the start index. Fixed.
